import {test} from 'node:test';
import assert from 'node:assert/strict';
import {makeIdentity,roomId} from '../src/protocol.ts';
import {inboxId,inboxRoom,parseInbox,sealDirect,openDirect,sealContacts,openContacts} from '../src/dm.ts';
import {encodeSession,decodeSession} from '../src/session.ts';
import {PortableStateRepository,generateMasterKey,CONTACT_COLLECTION,type RecordStore,type StoredRecord} from '../src/persistent/portable-state.ts';
test('inbox is derivable from a room signing identity; replies go to the sender',()=>{const alice=makeIdentity(),bob=makeIdentity(),mallory=makeIdentity();assert.equal(parseInbox(inboxId(bob.publicKey)),bob.publicKey);assert.equal(roomId(inboxRoom(bob.publicKey)),bob.publicKey);const packet=sealDirect(alice,bob.publicKey,'hello','Alice');assert.deepEqual(openDirect(bob,packet.payload),packet.message);assert.throws(()=>openDirect(mallory,packet.payload));assert.throws(()=>openDirect(alice,packet.payload));const reply=sealDirect(bob,openDirect(bob,packet.payload).sender,'hi');assert.equal(openDirect(alice,reply.payload).text,'hi');assert.notDeepEqual(packet.payload,sealDirect(alice,bob.publicKey,'hello','Alice').payload);});
test('tampering, malformed keys, wrong recipient and expired inbox packets fail closed',()=>{const a=makeIdentity(),b=makeIdentity(),packet=sealDirect(a,b.publicKey,'private');for(const i of [0,1,32,33,56,57,packet.payload.length-1]){const changed=packet.payload.slice();changed[i]^=1;assert.throws(()=>openDirect(b,changed));}assert.throws(()=>parseInbox('inbox1.'+'0'.repeat(64)));assert.throws(()=>openDirect(b,packet.payload,packet.message.time+8*86400000));assert.throws(()=>openDirect(b,packet.payload,packet.message.time-6000));assert.throws(()=>sealDirect(a,b.publicKey,' '));});
test('saved contacts are encrypted in session storage and bound to the identity',()=>{const a=makeIdentity(),b=makeIdentity(),contacts=[{publicKey:b.publicKey,name:'Bob'}];const encrypted=sealContacts(a,contacts);assert.deepEqual(openContacts(a,encrypted),contacts);assert.throws(()=>openContacts(b,encrypted));const raw=encodeSession({identity:a,rooms:[],contacts,language:'en'});assert.ok(!raw.includes(b.publicKey));assert.ok(!raw.includes('Bob'));assert.deepEqual(decodeSession(raw).contacts,contacts);});
class MemoryRecords implements RecordStore{records=new Map<string,StoredRecord>();async get(c:string,k:string){return this.records.get(c+'/'+k)?.value;}async list(c:string){return [...this.records.values()].filter(r=>r.collection===c);}async put(r:StoredRecord){this.records.set(r.collection+'/'+r.rkey,structuredClone(r));}async delete(c:string,k:string){this.records.delete(c+'/'+k);}}
test('archive restores encrypted contacts on a second device without exposing public keys in record IDs',async()=>{const key=await generateMasterKey(),local=new MemoryRecords(),remote=new MemoryRecords(),repo=new PortableStateRepository(key,local,remote),alice=makeIdentity(),bob=makeIdentity();await repo.saveIdentity(alice);await repo.saveContacts([{publicKey:bob.publicKey,name:'Bob'}]);const serialized=JSON.stringify(await remote.list(CONTACT_COLLECTION));assert.ok(!serialized.includes(bob.publicKey));assert.ok(!serialized.includes('Bob'));const restored=new PortableStateRepository(key,new MemoryRecords(),remote);await restored.pull();assert.deepEqual((await restored.restore('en'))?.contacts,[{publicKey:bob.publicKey,name:'Bob'}]);await repo.saveContacts([{publicKey:bob.publicKey,name:'Robert'}]);assert.equal((await remote.list(CONTACT_COLLECTION)).length,1);});

test('a sender cannot claim another signing identity',()=>{const a=makeIdentity(),b=makeIdentity(),victim=makeIdentity();const forged=sealDirect({...a,publicKey:victim.publicKey},b.publicKey,'forged');assert.throws(()=>openDirect(b,forged.payload));});

test('a damaged local contact list does not rotate the identity',()=>{const identity=makeIdentity(),raw=JSON.parse(encodeSession({identity,rooms:[],language:'en'}));raw.contacts='00';assert.equal(decodeSession(JSON.stringify(raw)).identity.publicKey,identity.publicKey);});
