import {openFile} from './attachments.ts';
import {roomId,type Attachment,type Room} from './protocol.ts';
import type {TextKey} from './i18n.ts';
import {preserveScroll} from './scroll.ts';
const cache=new Map<string,Promise<Blob>>(),objectUrls=new Map<string,string>();
const key=(room:Room,file:Attachment,preview=false)=>`${roomId(room)}:${preview&&file.preview?file.preview.id:file.original.id}`;
const load=(room:Room,file:Attachment,preview=false)=>{const id=key(room,file,preview);let value=cache.get(id);if(!value){value=openFile(room,file,preview);cache.set(id,value);value.catch(()=>cache.delete(id));}return value;};
const url=async(room:Room,file:Attachment,preview=false)=>{const id=key(room,file,preview);let value=objectUrls.get(id);if(!value){value=URL.createObjectURL(await load(room,file,preview));objectUrls.set(id,value);}return value;};
const size=(bytes:number)=>bytes<1024?`${bytes} B`:bytes<1048576?`${(bytes/1024).toFixed(1)} KB`:`${(bytes/1048576).toFixed(1)} MB`;
const button=(label:string,primary=false)=>{const value=document.createElement('button');value.type='button';value.textContent=label;if(primary)value.className='primary';return value;};
function markdown(blob:Blob,onRender:()=>void){const root=document.createElement('div');root.className='markdown-preview';void blob.text().then(source=>{const fragment=document.createDocumentFragment();let code:HTMLElement|undefined,list:HTMLUListElement|undefined;for(const line of source.slice(0,1_000_000).split(/\r?\n/)){if(line.startsWith('```')){if(code){fragment.append(code);code=undefined;}else code=document.createElement('pre');continue;}if(code){code.textContent+=(code.textContent?'\n':'')+line;continue;}const heading=/^(#{1,6})\s+(.*)$/.exec(line);if(heading){list=undefined;const h=document.createElement(`h${heading[1].length}`);h.textContent=heading[2];fragment.append(h);continue;}const item=/^[-*+]\s+(.*)$/.exec(line);if(item){if(!list){list=document.createElement('ul');fragment.append(list);}const li=document.createElement('li');li.textContent=item[1];list.append(li);continue;}list=undefined;if(!line.trim()){fragment.append(document.createElement('br'));continue;}const p=document.createElement('p');p.textContent=line;fragment.append(p);}if(code)fragment.append(code);root.replaceChildren(fragment);onRender();});return root;}
export function attachmentView(room:Room,file:Attachment,t:(key:TextKey,params?:Record<string,string|number>)=>string){const card=document.createElement('section');card.className='attachment-card';const head=document.createElement('div'),title=document.createElement('div'),name=document.createElement('strong'),info=document.createElement('small');name.textContent=file.name;info.textContent=`${size(file.bytes)} · ${file.mime}`;title.append(name,info);head.append(title);card.append(head);const stage=document.createElement('div');stage.className='attachment-stage';card.append(stage);const actions=document.createElement('div');actions.className='attachment-actions';const open=button(t('fileOpen')),download=button(t('fileDownload'),true);if(file.media==='file')open.hidden=true;actions.append(open,download);card.append(actions);const status=document.createElement('small');status.className='attachment-status';card.append(status);const reveal=async()=>{open.disabled=true;status.textContent=t('fileOpening');try{const preview=['image','video','audio'].includes(file.media)&&!!file.preview,blob=await load(room,file,preview),source=await url(room,file,preview),log=card.closest<HTMLElement>('.messages'),restore=log?preserveScroll(log):()=>{};stage.replaceChildren();let media:HTMLElement|undefined;if(file.media==='image'){const img=document.createElement('img');img.src=source;img.alt=file.name;media=img;stage.append(img);}else if(file.media==='video'){const video=document.createElement('video');video.src=source;video.controls=true;video.preload='metadata';video.playsInline=true;media=video;stage.append(video);}else if(file.media==='audio'){const audio=document.createElement('audio');audio.src=source;audio.controls=true;audio.preload='metadata';media=audio;stage.append(audio);}else if(file.media==='pdf'){const frame=document.createElement('iframe');frame.src=source;frame.title=file.name;media=frame;stage.append(frame);}else if(file.media==='markdown')stage.append(markdown(blob,restore));requestAnimationFrame(restore);media?.addEventListener(file.media==='image'||file.media==='pdf'?'load':'loadedmetadata',restore,{once:true});status.textContent='';open.hidden=true;}catch{status.textContent=t('fileUnavailable');open.disabled=false;}};open.onclick=()=>void reveal();download.onclick=()=>void(async()=>{download.disabled=true;status.textContent=t('fileOpening');try{const source=await url(room,file,false),a=document.createElement('a');a.href=source;a.download=file.name;a.click();status.textContent='';}catch{status.textContent=t('fileUnavailable');}finally{download.disabled=false;}})();if(file.media==='image')void reveal();return card;}
