import {nextRulesTime,type ConversationState} from './conversation-state.ts';
import type {Network} from './mesh-wire.ts';
import './conversation.css';
type Options={host:HTMLElement;preferences:HTMLElement;language:()=>string;persistent:()=>boolean;current:()=>string|undefined;items:()=>{id:string;name:string}[];state:(id:string)=>ConversationState;save:(state:ConversationState)=>Promise<void>;search:(query:string)=>void;identity:()=>{name:string;publicKey:string;rooms:string[];contacts:string[]};rename:(name:string)=>void;sync:()=>Promise<void>;reset:()=>Promise<void>;openChannel:(n:Network)=>void};
export function mountConversationTools(o:Options){
 const zh=()=>o.language()==='zh',label=(cn:string,en:string)=>zh()?cn:en;
 const toolbar=document.createElement('div');toolbar.className='conversation-tools';toolbar.hidden=true;
 const search=document.createElement('input');search.id='conversation-search';search.type='search';search.maxLength=200;search.autocomplete='off';search.oninput=()=>o.search(search.value);
 const settings=document.createElement('button');settings.id='conversation-settings';settings.type='button';toolbar.append(search,settings);o.host.querySelector('#messages')!.before(toolbar);
 const channelResults=document.createElement('div');channelResults.id='search-channels';toolbar.after(channelResults);
 const archive=document.createElement('button');archive.id='archive-open';archive.type='button';archive.className='archive-link';const share=o.preferences.querySelector('#profile-share');if(share)share.after(archive);else o.preferences.append(archive);
 const dialog=document.createElement('dialog');dialog.id='conversation-dialog';dialog.className='sheet';const head=document.createElement('div');head.className='sheet-head';const title=document.createElement('h2'),close=document.createElement('button');close.type='button';close.textContent='×';close.onclick=()=>dialog.close();head.append(title,close);const body=document.createElement('div');body.className='sheet-body';dialog.append(head,body);o.host.append(dialog);
 function field(text:string,input:HTMLElement){const el=document.createElement('label');el.textContent=text;el.append(input);return el;}
 function open(archiveView=false){
  body.replaceChildren();title.textContent=archiveView?'Archive':label('历史记录','History');
  const status=document.createElement('p');status.setAttribute('role','status');status.id='archive-feedback';
  if(archiveView){const identity=o.identity(),name=document.createElement('input');name.value=identity.name;name.maxLength=24;name.id='archive-name';const saveName=document.createElement('button');saveName.textContent=label('保存名称','Save name');saveName.onclick=()=>{try{o.rename(name.value);status.textContent=label('已保存','Saved');}catch{status.textContent=label('名称无效','Invalid name');}};const key=document.createElement('p');key.textContent=label('私钥：••••••••','Private key: ••••••••');const publicKey=document.createElement('code');publicKey.textContent=identity.publicKey;publicKey.className='identity-key';body.append(field(label('名称','Name'),name),saveName,publicKey,key);for(const [title,values] of [[label('房间','Rooms'),identity.rooms],[label('联系人','Contacts'),identity.contacts]] as const){const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent=title;details.append(summary);for(const name of values){const line=document.createElement('p');line.textContent=name;details.append(line);}body.append(details);}
   const sync=document.createElement('button');sync.textContent=label('检查并同步 Archive','Check and sync Archive');sync.onclick=()=>void(async()=>{sync.disabled=true;try{await o.sync();open(true);}catch{status.textContent=label('同步失败，请重试','Sync failed. Try again.');}finally{sync.disabled=false;}})();body.append(sync);
  }
  const items=o.items(),select=document.createElement('select');select.id='conversation-select';for(const item of items){const option=document.createElement('option');option.value=item.id;option.textContent=item.name;select.append(option);}if(o.current())select.value=o.current()!;
  select.hidden=!archiveView;body.append(select);const form=document.createElement('form');form.id='conversation-rules';
  const since=document.createElement('input');since.id='history-since';since.type='datetime-local';
  const hidden=document.createElement('textarea');hidden.id='hidden-messages';hidden.rows=3;const blocked=document.createElement('textarea');blocked.id='blocked-users';blocked.rows=3;
  const save=document.createElement('button');save.className='primary';save.textContent=label('保存','Save');
  const clear=document.createElement('button');clear.type='button';clear.textContent=label('不限时间','All available history');clear.onclick=()=>since.value='';
  form.append(field(label('开始时间','Start time'),since),clear,field(label('屏蔽的消息 ID','Hidden message IDs'),hidden),field(label('屏蔽的用户公钥','Blocked user public keys'),blocked),save);body.append(form);
  const position=document.createElement('small');position.id='reading-position';body.append(position);
  const load=()=>{const id=select.value;if(!id){form.hidden=true;return;}form.hidden=false;const state=o.state(id);since.value=state.since===null?'':new Date(state.since-new Date(state.since).getTimezoneOffset()*60000).toISOString().slice(0,16);hidden.value=state.hidden.join('\n');blocked.value=state.blocked.join('\n');position.textContent=state.position?label('上次浏览：','Last viewed: ')+new Date(state.position.time).toLocaleString()+ ' · '+state.position.id:label('尚无浏览位置','No reading position');};select.onchange=load;load();
  form.onsubmit=e=>{e.preventDefault();void(async()=>{save.disabled=true;try{const state={...o.state(select.value),since:since.value?new Date(since.value).getTime():null,hidden:[...new Set(hidden.value.split(/\s+/).filter(Boolean))],blocked:[...new Set(blocked.value.split(/\s+/).filter(Boolean))],rulesAt:nextRulesTime(o.state(select.value))};await o.save(state);status.textContent=label('已保存','Saved');}catch{status.textContent=label('保存失败，请检查时间、消息 ID 和用户公钥','Could not save. Check time, message IDs and public keys.');}finally{save.disabled=false;}})();};
  if(archiveView){const warning=document.createElement('p');warning.className='recovery-warning';warning.textContent=label('重置后旧文件不能恢复当前账户。请保存新文件；已下载的旧备份和已解密数据无法撤回。','Resetting replaces the recovery secret. Save the new file. Downloaded old backups and decrypted data cannot be revoked.');const reset=document.createElement('button');reset.id='archive-reset-recovery';reset.className='danger';reset.textContent=label('重新生成恢复文件','Reset recovery file');reset.onclick=()=>{if(!confirm(warning.textContent!))return;void(async()=>{reset.disabled=true;try{await o.reset();status.textContent=label('请保存新的恢复文件','Save your new recovery file');}catch(error){status.textContent=error instanceof Error&&error.message==='Recovery reset; download pending'?label('恢复文件已重置。请在身份设置中下载新文件。','Recovery file reset. Download the new file in identity settings.'):label('重置失败，请检查登录和网络后重试','Reset failed. Check sign-in and network, then retry.');}finally{reset.disabled=false;}})();};body.append(warning,reset);}
  body.append(status);document.querySelectorAll<HTMLDialogElement>('dialog[open]').forEach(d=>d.close());dialog.showModal();
 }
 settings.onclick=()=>open();archive.onclick=()=>open(true);
 return {render(){toolbar.hidden=!o.current();archive.hidden=!o.persistent();archive.textContent=label('Archive 内容管理','Manage Archive');search.placeholder=label('搜索消息、文件、频道','Search messages, files, channels');search.setAttribute('aria-label',search.placeholder);settings.textContent=label('历史记录','History');close.setAttribute('aria-label',label('关闭','Close'));},clear(){search.value='';channelResults.replaceChildren();o.search('');},channels(items:Network[]){channelResults.replaceChildren();for(const n of items){const button=document.createElement('button');button.textContent=n.name;button.onclick=()=>o.openChannel(n);channelResults.append(button);}},dialog};
}
