const clean=(value:string|undefined)=>value?.trim().replace(/\/+$/,'')||'';
const viteEnv=(import.meta as ImportMeta&{env?:Record<string,string|undefined>}).env||{};
export const storageBase=clean(viteEnv.VITE_STORAGE_URL);
const messageStoreBase=clean(viteEnv.VITE_WAKU_STORE_URL)||storageBase;
const managedBase=storageBase||'https://storage.wakukusmartrecipe.uk';
const routeBases:string[]=(viteEnv.VITE_LOGOS_STORAGE_ROUTES||'').split(',').map((value:string)=>clean(value)).filter(Boolean);
export type StorageRoute={baseUrl:string;priority:number;managedSoftRoom:boolean};
export const storageRoutes:StorageRoute[]=[{baseUrl:managedBase,priority:1000,managedSoftRoom:true},...routeBases.filter(baseUrl=>baseUrl!==managedBase).map((baseUrl,index)=>({baseUrl,priority:100-index,managedSoftRoom:false}))].sort((a,b)=>b.priority-a.priority);
const jsonHeaders={'Content-Type':'application/json'};
const bytesToBase64=(bytes:Uint8Array)=>{let result='';for(let i=0;i<bytes.length;i+=0x8000)result+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(result);};
const base64ToBytes=(value:string)=>Uint8Array.from(atob(value),c=>c.charCodeAt(0));
const hex=(bytes:Uint8Array)=>Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');
const logosCid=(value:string)=>/^[A-Za-z0-9]{20,200}$/.test(value)&&!/^[a-f0-9]{64}$/.test(value);
async function sha256(data:Uint8Array){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',data.slice().buffer)));}
async function checked(input:string,init?:RequestInit){const response=await fetch(input,init);if(!response.ok)throw Error(`Storage ${response.status}`);return response;}
async function routedFetch(input:string,init?:RequestInit){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),180000);try{return await fetch(input,{...init,signal:controller.signal});}finally{clearTimeout(timer);}}
// Message history remains on the Waku Store manager. Logos Storage carries attachment bytes only.
export async function backupMessage(roomId:string,payload:Uint8Array){if(messageStoreBase)await checked(messageStoreBase+'/v1/messages',{method:'POST',headers:jsonHeaders,body:JSON.stringify({roomId,payload:bytesToBase64(payload)})});}
export async function pushViaWakuStore(roomId:string,payload:Uint8Array){if(!messageStoreBase)throw Error('Waku Store unavailable');await checked(messageStoreBase+'/v1/messages',{method:'POST',headers:jsonHeaders,body:JSON.stringify({roomId,payload:bytesToBase64(payload)})});}
export async function storageHistory(roomId:string,receive:(payloads:Uint8Array[])=>void,signal?:AbortSignal){if(!messageStoreBase)throw Error('Storage unavailable');let before:string|undefined;for(let page=0;page<10;page++){const query=new URLSearchParams({limit:'100'});if(before)query.set('before',before);const response=await checked(`${messageStoreBase}/v1/rooms/${roomId}/messages?${query}`,{signal});const value=await response.json() as {messages?:{payload:string}[];nextBefore?:number};const payloads=(value.messages||[]).map(item=>base64ToBytes(item.payload));if(payloads.length)receive(payloads);if(!value.nextBefore)break;before=String(value.nextBefore);}}
export type UploadProgress={phase:'processing'|'encrypting'|'uploading'|'opening';loaded:number;total:number};
export type StoredObject={id:string;size:number;storage:'logos';cipherSha256:string};
async function uploadToRoute(route:StorageRoute,roomId:string,data:Uint8Array){const headers=new Headers({'Content-Type':'application/octet-stream','Content-Disposition':'attachment; filename="encrypted.bin"'});if(route.managedSoftRoom)headers.set('X-Soft-Room-Id',roomId);const response=await routedFetch(`${route.baseUrl}/api/storage/v1/data`,{method:'POST',headers,body:new Blob([data.slice().buffer])});if(!response.ok)throw Error(`Storage ${response.status}`);const cid=(await response.text()).trim();if(!/^[A-Za-z0-9]{20,200}$/.test(cid))throw Error('Invalid Storage CID');return cid;}
export async function uploadObject(roomId:string,data:Uint8Array,progress?:(value:UploadProgress)=>void):Promise<StoredObject>{const cipherSha256=await sha256(data);let last:unknown;progress?.({phase:'uploading',loaded:0,total:data.length});for(const route of storageRoutes)try{const id=await uploadToRoute(route,roomId,data);progress?.({phase:'uploading',loaded:data.length,total:data.length});return{id,size:data.length,storage:'logos',cipherSha256};}catch(error){last=error;}throw last||Error('Storage unavailable');}
async function read(response:Response,progress?:(value:UploadProgress)=>void){const total=Number(response.headers.get('Content-Length'))||0;if(!response.body)return new Uint8Array(await response.arrayBuffer());const reader=response.body.getReader(),parts:Uint8Array[]=[];let loaded=0;for(;;){const {done,value}=await reader.read();if(done)break;parts.push(value);loaded+=value.length;progress?.({phase:'opening',loaded,total});}const output=new Uint8Array(loaded);let offset=0;for(const part of parts){output.set(part,offset);offset+=part.length;}return output;}
async function logosDownload(id:string,progress?:(value:UploadProgress)=>void,expectedSha256?:string){let last:unknown;for(const route of storageRoutes)try{const response=await routedFetch(`${route.baseUrl}/api/storage/v1/data/${encodeURIComponent(id)}/network/stream`);if(!response.ok)throw Error(`Storage ${response.status}`);const output=await read(response,progress);if(expectedSha256&&await sha256(output)!==expectedSha256)throw Error('Storage hash mismatch');return output;}catch(error){last=error;}throw last||Error('Storage unavailable');}
export async function downloadObject(roomId:string,id:string,progress?:(value:UploadProgress)=>void,expectedSha256?:string){const output=logosCid(id)?await logosDownload(id,progress,expectedSha256):await read(await checked(`${messageStoreBase}/v1/files/${roomId}/${id}`),progress);if(!logosCid(id)&&expectedSha256&&await sha256(output)!==expectedSha256)throw Error('Storage hash mismatch');return output;}
